### ISSUE TITLE
Simple Addition to PGVES

### ISSUE THREAD

**Issue by Harmonickey** [LbKStudios/lbkstudios-main#135]
Remove Progressive Dynamics,
Add LbKStudios LLC

**Comment by Harmonickey** [comment]
Just waiting on Jeff now.

**Comment by Harmonickey** [comment]
New Updates.

![ves notes for lbk](https://cloud.githubusercontent.com/assets/3519788/5656214/9596bd28-969e-11e4-954c-ba2f5ceb7dec.png)
![ves notes for lbk2](https://cloud.githubusercontent.com/assets/3519788/5656215/9596e118-969e-11e4-9a9d-cd9637d9b150.png)

**Comment by Harmonickey** [comment]
Does the code check out?  Does it work for you?

**Comment by Saurutobi** [comment]
Gimme a sample file to test on

**Comment by Harmonickey** [comment]
Sent off the last revision.  Works pretty well now.

**Comment by Saurutobi** [comment]
Failed, it doesn't seem to be working. steps:
1.Open test doc.xlsx to make sure stuff is there
2.I executed the 92KB VendorExcelSplice.exe in the /bin/Release dir.
3.click select File button
4.Select *.xlsx in the file type box on the bottom right
5.Select test doc.xlsx
6.paste "271185" in the row match box
7.Move radio button to Delete
8.change output format from text doc~[some numbers].xlsx to test doc2.xlsx
9.clicked on save, then on the X on the popup. Warning about directory not being made pops up, close.
10.Find c:\\VendorExcelSplice dir, delete it(it got made in step 9)
11.click Execute. [First half of output from here] CHECKED BOTH FILES, DIDN'T WORK
12.Moved radio button to Keep
13.Execute again. [more output] CHECKED BOTH FILES, DIDN'T WORK

That's my steps, that's where I left it. I'll look at the code and see what's up.

log:
Set input and output files...
Saving Session: 
Validated inputs...
Opened C:\Users\Saurutobi\Desktop\test doc.xlsx
Number of Rows: 43
Deleted Rows: 0
Number of Rows: 43
Deleted Rows: 0
Number of Rows: 43
Deleted Rows: 0
Saved Output to C:\Users\Saurutobi\Desktop\test doc2.xlsx
Finished Executing!
Validated inputs...
Opened C:\Users\Saurutobi\Desktop\test doc.xlsx
Number of Rows: 43
Deleted Rows: 0
Number of Rows: 43
Deleted Rows: 0
Number of Rows: 43
Deleted Rows: 0
Saved Output to C:\Users\Saurutobi\Desktop\test doc2.xlsx
Finished Executing!


![untitled](https://cloud.githubusercontent.com/assets/4614977/5697457/18c83258-99bf-11e4-828a-f667b474549a.png)

**Comment by Harmonickey** [comment]
Oh.  I know why that happened.  xlsx is saved in binary format

**Comment by Harmonickey** [comment]
I would rather not recode it to work with all sorts of excel files right now.  It works for the needs of ProgressiveDynamics because they save their excel files as HTML for some reason.  They won't change that apparently.  If they did somehow start saving their files as xlsx without the HTML, then we would need to update the application.  The problem I was having before was the fact that it wasn't keeping the original formatting of the headers for some reason and it wasn't clear how to keep it once read into C# since their HTML formatting is very weird and C# just erases the formatting upon load.

**Comment by Saurutobi** [comment]
ok, then let's disable .xlsx input altogether. Or, we can enable it, but only output xls, but I don't think that'll work.

**Comment by Harmonickey** [comment]
I don't think that'll work since they just don't save their files as
binary.  It won't make a difference for xlsx or xls since they're both
saved as binary normally, until they actually decide to save their excel
files like the rest of the world.

Try with the new input file that I sent to you.

On Sun, Jan 11, 2015 at 5:55 PM, Saurutobi <notifications@github.com> wrote:

> Assigned #135 <https://github.com/LbKStudios/lbkstudios-main/issues/135>
> to @Harmonickey <https://github.com/Harmonickey>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/135#event-217159702>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Saurutobi** [comment]
looks good

**Comment by Saurutobi** [comment]
hold on, I'm gonna fail it again.
what's this folder that it made?

I put QA Failed on this. I accidentally bumped it to QA Passed instead of Code Review Passed. it should have then gone to ready for QA and then In QA and then failed. That's my mistake.

**Comment by Harmonickey** [comment]
Wait, what?  It's supposed to create a folder to store its saved configs.
What is the foldername?

**Comment by Saurutobi** [comment]
it was the file name+files

**Comment by Harmonickey** [comment]
I don't get this effect.  I remember this happening before, but I fixed it
for sure.  It was a problem with using Excel.Interopt but since I'm not
using it anymore, it shouldn't happen.

This makes me think that you either didn't pull down the latest version of
the code, or didn't uninstall the previous version from your system before
installing the new version of the published code.

On Thu, Jan 15, 2015 at 5:33 PM, Saurutobi <notifications@github.com> wrote:

> it was the file name+files
>
> On Thu, Jan 15, 2015 at 6:22 PM, Alex Ayerdi <notifications@github.com>
> wrote:
>
> > Wait, what? It's supposed to create a folder to store its saved configs.
> > What is the foldername?
> > On Jan 15, 2015 4:58 PM, "Saurutobi" <notifications@github.com> wrote:
> >
> > > hold on, I'm gonna fail it again.
> > > what's this folder that it made?
> > >
> > > I put QA Failed on this. I accidentally bumped it to QA Passed instead
> > of
> > > Code Review Passed. it should have then gone to ready for QA and then
> In
> > QA
> > > and then failed. That's my mistake.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/LbKStudios/lbkstudios-main/issues/135#issuecomment-70178961>
>
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/LbKStudios/lbkstudios-main/issues/135#issuecomment-70182058>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/135#issuecomment-70183373>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Saurutobi** [comment]
Maybe didnt pull. I also didn't run theinstall, just the executable. Also, the gitignore isn't getting those debug and release folders. Imma investigate

**Comment by Harmonickey** [comment]
hmm, yeah.  It definitely works for me.  Still waiting on what Jeff thinks about it.

**Comment by Saurutobi** [comment]
Does Jeff like it? I would like to send this up the branches with 144

**Comment by Harmonickey** [comment]
I'll message him soon about it, he's been quiet so far.

**Comment by Harmonickey** [comment]
paid
