### ISSUE TITLE
LbKStudios goes into Film

### ISSUE THREAD

**Issue by Saurutobi** [LbKStudios/lbkstudios-main#142]
I'm going to get this started. I've made a youtube channel for us.
I've gotta decorate it and whatnot, but that's gotta wait until Joe gets the logo done.

I plan on doing a small commercial type thing for us that we can post on the website.
Also, all the videos for drpTV can be on here. Plus, when we start getting contracts for film we can put them here.

**Comment by Harmonickey** [comment]
Sure, sounds good.

**Comment by Harmonickey** [comment]
All of the mini-scripts in the dropbox folder are hilarious!

**Comment by Saurutobi** [comment]
right?! I just kinda stuck them all in there because I needed it in dropbox
for my tablet, and in there made the most sense. I've been slowly just
making files with ideas, and then working on them when I get more ideas or
decide to focus.

How To: Be a Man is my favorite right now, next to We Saved the PRON!
