### ISSUE TITLE
Fluent Edits

### ISSUE THREAD

**Issue by Harmonickey** [LbKStudios/lbkstudios-main#144]
~~1. Typo on title page, namely a space needs to be between "film" and "radio," and "lecture" and "conference."~~
~~2. Change copyright to 2015~~
~~3. Change text to left-justified.~~
~~4. Transfer changes to mobile version too.~~

**Comment by Harmonickey** [comment]
Please check out to see if it works.  Just load it up from the repo, I don't think I'll upload to the /test location since we're just fixing typos and such.

**Comment by Saurutobi** [comment]
ok, I'll do it as soon as I get back home tonight.

**Comment by Saurutobi** [comment]
It's all good. Should I push it up through the branches?

**Comment by Harmonickey** [comment]
Yessir

**Comment by Harmonickey** [comment]
I don't see my changes in master.  Did you push when you propagated through the branches?

**Comment by Saurutobi** [comment]
not yet. gimme a sec

**Comment by Saurutobi** [comment]
there, all yours. branch has been nuked, make sure to delete your local

**Comment by Harmonickey** [comment]
sweet.  thanks, it's all uploaded to production
