### ISSUE TITLE
LoadDoctor Phase 2: Additions

### ISSUE THREAD

**Issue by Harmonickey** [LbKStudios/lbkstudios-main#148]
~~Remove Best Bid Carrier~~
~~Add in My Last Bid~~
~~Add in My Rank~~
~~Make sure all data is loaded into table upon the tables loading (best bid, etc)~~
~~Default DurationTime to 01:00 (in the auction bidder frame)~~

~~Change "Status 1" to "Itineraries"~~
    ~~Countdown stays as is~~

~~Change "Status 0" to "Last Minutes Orders"~~
    ~~Separate countdown for each order~~
~~- Create new Bid table for Last Minutes Orders (Bid2?)~~
    ~~- Remove Trucks column, add in Loads column, add in MinDate & MaxDate columns~~

**Comment by Saurutobi** [comment]
None of this was in the contract.

**Comment by Harmonickey** [comment]
apparently it was, but it wasn't clear?  what do you think we should do
about it?  we could always move it over to phase 3?

On Sun, Feb 1, 2015 at 11:19 AM, Saurutobi <notifications@github.com> wrote:

> None of this was in the contract.
>
>
>
> > On Feb 1, 2015, at 11:57, Alex Ayerdi <notifications@github.com> wrote:
> >
> > Remove Best Bid Carrier
> > Add in My Last Bid
> > Add in My Rank
> > Make sure all data is loaded into table upon the tables loading (best
> bid, etc)
> > Change "Status 1" to "Itineraries"
> > Countdown stays as is
> > Change "Status 0" to "Last Minutes Orders"
> > Separate countdown for each order
> > Create new Bid table for Last Minutes Orders (Bid2?)
> > Remove Trucks column, add in Loads column, add in MinDate & MaxDate
> columns
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/148#issuecomment-72373650>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Harmonickey** [comment]
Almost done with this.  I have most the code written up.  Need to implement the functions that grab the latest bidding data.  Best Bid, user's Last Bid, user's Rank.  The last two respectively if the user even has a bid.

**Comment by Harmonickey** [comment]
Will need to make separate call to bid table to get user's last bid and their rank, along with the minimum bid.  It's not feasible to do it in the trucks and loads call.  I got a successful join to happen (in mysql it's a bitch because I wanted a full outer join, but you have to do a left outer -> union all -> right outer) but it has too much data in it to parse.  What I get is a bunch of redundant rows because there are many bids for a single truck, but in that response what I really want is just a single truck in a row.  So that's why I am changing to a separate bid table call instead.  (I dunno if ANY of that made sense)

**Comment by Harmonickey** [comment]
Just check it out in terms of functionality.  You can look at the code too if you want.

**Comment by Saurutobi** [comment]
looks good. I can't say I'm particularily happy with the interface(something just feels off), but I'm not unhappy. I think Hami will definitely like it though.

anyways, it passes.
