### ISSUE TITLE
drpTV Updates, Again

### ISSUE THREAD

**Issue by Saurutobi** [LbKStudios/lbkstudios-main#149]
~~-Nav bar: make link hover Gold from purple~~
~~-Video Slider: Change Playback button color to gold like Logo~~
~~-Video Slider: Buttons don't place properly~~
~~-Trusted By: Add a space above like one that exists below~~
~~-Trusted By: Links to testimonial page not working~~
~~-Testimonials: Links need to open in new tab~~
~~-Testimonials: Gold bar needs to either go away or box the entire section~~
~~-Debbie Ryan's Cover title is not proper. missing the 's'. Also, it's 'debby'~~
~~-Main page View All button: Fill button with purple, white text~~
~~-drptv.lbkstudios.net/videos: audio not working properly~~
~~-drptv.lbkstudios.net/videos: fullscreen not working properly~~
~~-Production Page: each sentence on new line, doublecheck text from email~~
~~-Tech Page: each sentence on new line~~
~~-Creative Page: each sentence on new line, last sentence needs period~~
~~-Contact Us Page: send emails to Asst@drptv.com. If possible, send Job ones also to HR@drptv.com~~
-Password Protected page
~~-Fix Don Henley Walden Woods Sweepstakes link:https://www.chideo.com/chideo/2021~~
~~-Remove Chris Paul Celebrity Service. It's broken~~
-Add Melissa Joan Hart Video from drptv.com
~~-Off Their Rockers image to:http://www.nbc.com/sites/nbcunbc/files/files/styles/nbc_show_about_cover/public/images/2013/12/10/2013_1122_Off_Their_Rockers_Show_Key_Art_1920x1080_ES_1.jpg?itok=YaxRTlfv~~
~~-drpTV sizzle reel image to drpTV Logo~~
~~-VideoJs, any where this is it needs that php shit~~

**Comment by Saurutobi** [comment]
@Harmonickey a lot of this I can tackle Friday night or Saturday. If I have problems, I'll let you know asap.

**Comment by Harmonickey** [comment]
Okay, sounds good.  I knew the video fullscreen problem.  Some sort of Swell styling thing with videos.  It now fullscreens just fine.  The audio is weird and I sent you a screenshot of the element on the page that isn't being updated properly, as well as the sibling element to it.  It is not CSS because I would have seen it in the right hand side pane, so it's a javascript change to the element directly, which you are best at looking for with Firefox.

**Comment by Saurutobi** [comment]
@Harmonickey videojs: you've muting all players in MuteEvent(), but I have no idea how to hook into that and disable it for the http://drptv.lbkstudios.net/videos/ page. I don't actually know where you put the file on the server.

fix: on line 13, between num_videos=bla and initial_findControlLocation() put these lines:

if(document.URL == ""http://drptv.lbkstudios.net/videos/")
{
lbk_muted = false;
}

That should do it.

**Comment by Saurutobi** [comment]
if you get to this before me(cuz I'm going home now), can you please update the ftp details on the spreadsheet? I don't have that stuff saved anymore. If I get to it before you later tonight I'll do it myself.

**Comment by Harmonickey** [comment]
Ooohhhh fuck!!!!! Good catch.  Did you fix it?

**Comment by Saurutobi** [comment]
fixed the problem, but I don't like the result. clikcing on the mute button won't mute now. Is there any way to just disable the js file on this page?

**Comment by Harmonickey** [comment]
yes, go into the php, head.php (I think), and don't load it when it had a
certain page tag.  There is already code there for other files that I
include/exclude, which you can copy the logic for.

On Sun, Feb 8, 2015 at 4:09 PM, Saurutobi <notifications@github.com> wrote:

> fixed the problem, but I don't like the result. clikcing on the mute
> button won't mute now. Is there any way to just disable the js file on this
> page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/149#issuecomment-73435148>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Saurutobi** [comment]
I knocked out a bunch more of the super basic stuff. just took a bunch of time but they're done.

**Comment by Harmonickey** [comment]
sweet dude.  this is making life so much easier

On Sun, Feb 8, 2015 at 6:50 PM, Saurutobi <notifications@github.com> wrote:

> I knocked out a bunch more of the super basic stuff. just took a bunch of
> time but they're done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/149#issuecomment-73443622>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Saurutobi** [comment]
omg this button is pissing me off. super hax. it's now an image:)

**Comment by Harmonickey** [comment]
da fuck...

On Sun, Feb 8, 2015 at 8:26 PM, Saurutobi <notifications@github.com> wrote:

> omg this button is pissing me off. super hax. it's now an image:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/149#issuecomment-73448875>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Harmonickey** [comment]
I think I figured out the video control buttons.  Check it out.

**Comment by Saurutobi** [comment]
IT FUCKING WORKS!!!!!

**Comment by Harmonickey** [comment]
I iz geniuz

On Tue, Feb 10, 2015 at 2:08 PM, Saurutobi <notifications@github.com> wrote:

> IT FUCKING WORKS!!!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/149#issuecomment-73773779>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Harmonickey** [comment]
Also, I'm fucking retarded...


On Tue, Feb 10, 2015 at 2:10 PM, Alex Ayerdi <
alexanderayerdi2015@u.northwestern.edu> wrote:

> I iz geniuz
>
> On Tue, Feb 10, 2015 at 2:08 PM, Saurutobi <notifications@github.com>
> wrote:
>
>> IT FUCKING WORKS!!!!!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/LbKStudios/lbkstudios-main/issues/149#issuecomment-73773779>
>> .
>>
>
>
>
> --
> Northwestern University Class of 2015
> Weinberg College of Arts and Sciences, Computer Science Major
> AlexanderAyerdi2015
> *@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
> 1-269-267-3752*
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Harmonickey** [comment]
Unfortunately, the web developer will have to add page titles to the list of bad web pages to use videoControl.js on.  However, I made it work.  The project pages don't have normal $post titles, so it's super difficult to have maintainability, but I think it'll be fine.

**Comment by Harmonickey** [comment]
Moved the styles in home page editor to be in Customize editor.  I also moved the blockquote styling to be there as well so it applies to all testimonial blockquotes.  The video controls are exactly the yellow of the DRPtv logo now.

**Comment by Harmonickey** [comment]
Bug fixes on videos' video control on fullscreen, social stream player, and dimming.

The social stream issue was some input coming in from an ajax request that wasn't removed of ">" and "<" characters.  They messed up some jQuery calls later and make half of the social stream not popup when that ajax event occurs.  I fixed it by strictly replacing the characters.

**Comment by Harmonickey** [comment]
In addition, I modified functions.php to have a more efficient way of loading our custom scripts.  Now they load on the specific pages that they are needed.  The website runs considerably faster now.
