### ISSUE TITLE
LoadDoctor Phase 2: Fixes

### ISSUE THREAD

**Issue by Harmonickey** [LbKStudios/lbkstudios-main#150]
~~- All Text boxes need to be blank on submit.~~
~~- Popup notification on successful submit, but it goes away after a second.~~
~~- Only store comments for now, do not display~~
~~- Remove x's from status=0 queries~~
~~- Only store mindate and maxdate for now, do not display~~
    ~~- remove displaying from best-bid box~~
~~- Carrier can bid anything they want, but only the last bid matters~~
~~- store the old bid in a separate table for later use (old_bids)~~

**Comment by Harmonickey** [comment]
This is super easy stuff to do.  I just made assumptions about certain things in the platform.  Once those are fixed, then it looks like it's good to go.

**Comment by Saurutobi** [comment]
Ok. I saw he wanted you to make another table?

**Comment by Harmonickey** [comment]
Actually I suggested that since it'll make filtering the 'bid' table easier.  Well... I suppose we don't NEED another table... we could just only use their 'last' bid by taking the earliest bid when you filter by date.

**Comment by Harmonickey** [comment]
The whole idea is that they user can always add as many bids as they want, higher or lower than the best bid.  The last bid is the only one that gets displayed though, and their other bids do not matter.  He literally said that to me, but he doesn't want to delete the data (which is reasonable, "data is power").

**Comment by Saurutobi** [comment]
Storing it makes sense for historic purposes, so i understand that. The different table thing hurts my designer heart but it will do fine for any and all purposes, and make the tables easier to look at.

**Comment by Harmonickey** [comment]
Exactly, that's what I thought too.

**Comment by Harmonickey** [comment]
make sure it has the desired qualities in the description.  this was super easy to do.  if you don't feel like it, you can just pass it for now (or not?)

**Comment by Saurutobi** [comment]
looks like its good.

**Comment by Harmonickey** [comment]
I actually optimized the bid gathering, so that it's all total only three queries.  Super fast now.  We are done with this, the contract is closed out, just waiting on the check to arrive.
