### ISSUE TITLE
BLAST Updates

### ISSUE THREAD

**Issue by Harmonickey** [LbKStudios/lbkstudios-main#151]
~~Once the BLAST website is moved to Bluehost I think it'd be cool to use Elegant Themes to give the website a sweet and modern look.  We'll have to decide on what sort of genre to use (blog won't be good, for example) and then simply apply it.  We should put all the stuff in its own separate subdomain that we can work with and then transfer over to production when we think it's good.~~

~~I really like the TheSource theme, but we should check out others.~~

~~It'll make the website more maintainable as well as better looking.  It would be an excellent addition to our portfolio as well as competitive against other dance groups on Northwestern's campus.  There is no pressure involved and no deadline.~~

~~Work on getting the front page to be static informational and have news/blog/etc on separate page(s)~~

**Comment by Saurutobi** [comment]
When will it be migrated?

**Comment by Harmonickey** [comment]
Sometime within the next few weeks.  I'm still trying to convince them.

On Wed, Feb 11, 2015 at 11:55 AM, Saurutobi <notifications@github.com>
wrote:

> When will it be migrated?
>
>
>
> > On Feb 11, 2015, at 12:24, Alex Ayerdi <notifications@github.com> wrote:
> >
> > Once the BLAST website is moved to Bluehost I think it'd be cool to use
> Elegant Themes to give the website a sweet and modern look. We'll have to
> decide on what sort of genre to use (blog won't be good, for example) and
> then simply apply it.
> >
> > It'll make the website more maintainable as well as better looking. It
> would be an excellent addition to our portfolio as well as competitive
> against other dance groups on Northwestern's campus. There is no pressure
> involved and no deadline.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/151#issuecomment-73929307>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Harmonickey** [comment]
We are ready to begin using Elegant Themes to update the website.  This'll be awesome for our portfolio!

**Comment by Harmonickey** [comment]
moved site to test.blastnu.org , once you choose a theme can you install the elegant theme into the website?

**Comment by Saurutobi** [comment]
no.


jk, sure

**Comment by Harmonickey** [comment]
This is looking pretty good.  They want a few changes to the front page though.  Instead of blog-style, they want the blog on another page with update/news/etc  but the front page have static informational stuff so that "If someone is coming to our website for the first time we want to hit them with what we are and what we can do"

**Comment by Harmonickey** [comment]
This is good now too
