### ISSUE TITLE
Javascript Compiler Google Extension App

### ISSUE THREAD

**Issue by Harmonickey** [LbKStudios/lbkstudios-main#152]
This can be an extension that just runs on document-load when it's activated in the Extensions list.  Then it checks all the function symbol definitions and cross-references with the IDs in the DOM.  If there are any conflicts, then notify the user somehow.  The notification can just be an alert, or a console.log for now.

We will need to learn how to create Chrome Extensions/Add-on.  We could extend this to Firefox as well, since it's a popular platform.  Fuck IE.

**Comment by Harmonickey** [comment]
This is the function I wrote to match one type of function in Javascript
Capture "function name()"
`for (var i = 0; i < javascriptFileLines.length; i++) {
    if (javascriptFileLines[i].match(/function \S+\(/)) { 
        console.log(javascriptFileLines[i]); 
    } 
}`

**Comment by Harmonickey** [comment]
To get the javascriptFileLines, I suggest we do....
var javascriptFile = "";
$.get('javascript relative file location', function(res) { javascriptFile = res;});
javascriptFileLines = javascriptFile.split("\n")

**Comment by Harmonickey** [comment]
To match
var functionName = function()
```
for (var i = 0; i < javascriptFileLines.length; i++) {
    if (javascriptFileLines[i].match(/var \S+ = function\(/)) { 
        console.log(javascriptFileLines[i]); 
    } 
}
```

**Comment by Harmonickey** [comment]
Of course, this is all assuming that everyone formats their code nicely

**Comment by Harmonickey** [comment]
Actually, this way is better
```
function getAllFunctions(){ 
      var myfunctions = [];
      for (var l in this){
        if (this.hasOwnProperty(l) && 
            this[l] instanceof Function &&
            !/myfunctions/i.test(l)){
          myfunctions.push(this[l]);
        }
      }
      return myfunctions;
}
```

**Comment by Harmonickey** [comment]
Then we'd cross-reference with this...
```
var allElements = document.getElementsByTagName("*");
var allIds = [];
for (var i = 0, n = allElements.length; i < n; ++i) {
  var el = allElements[i];
  if (el.id) { allIds.push(el.id); }
}
```

**Comment by Saurutobi** [comment]
I can't say it'll be easy from the looks of it.

**Comment by Harmonickey** [comment]
It actually should be quite easy since we just need to write javascript.

The only hard part is creating the parameters file for chrome extensions,
it's a weird syntax, but should be easy enough to learn in a day.

Alex

On Sat, Mar 7, 2015 at 12:37 PM, Saurutobi <notifications@github.com> wrote:

> I can't say it'll be easy from the looks of it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/152#issuecomment-77703011>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*
