### ISSUE TITLE
BLAST Migration

### ISSUE THREAD

**Issue by Harmonickey** [LbKStudios/lbkstudios-main#153]
We need to move BLAST to Bluehost

~~1. Migrate Files~~

~~2. Migrate MySQL Database tables~~

~~3. Update Autorenewal on Bluehost - turn off~~

~~4. Update forwarding on GoDaddy - turn off~~

~~5. Update config files on website if need be - point to database, website url, etc...~~
~~User: blastnuo_wo2296 Password: Vpssql061!~~
~~Database: blastnuo_blast~~
~~6. Update database rows to reflect website url, relative urls, etc...~~
~~7. Remove permalink structure~~

**Comment by Saurutobi** [comment]
Is it wordpress? Do we have access to the bluehost?

**Comment by Harmonickey** [comment]
It is wordpress.  The bluehost credentials are in Login.xlsx.  I am asking
for permission to phpMyAdmin first from our student government.  Once I
have the database backup then we can do the actual transfer, but for now we
can only do the files.

On Sat, Mar 7, 2015 at 10:52 PM, Saurutobi <notifications@github.com> wrote:

> Is it wordpress? Do we have access to the bluehost?
>
>
>
> > On Mar 7, 2015, at 23:50, Alex Ayerdi <notifications@github.com> wrote:
> >
> > We need to move BLAST to Bluehost
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/153#issuecomment-77733210>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Saurutobi** [comment]
Alright. Sounds good

**Comment by Harmonickey** [comment]
I think there is some forwarding setup on GoDaddy (I know, I know...) so we'll have to take that off once we have mysql access.

**Comment by Saurutobi** [comment]
Yea, it's just a nameserver thing. Next time they renew domain have them renew through bluehost

**Comment by Harmonickey** [comment]
cool, should happen around September.  I may just do it for them so they
don't fuck up.

On Sat, Mar 7, 2015 at 11:47 PM, Saurutobi <notifications@github.com> wrote:

> Yea, it's just a nameserver thing. Next time they renew domain have them
> renew through bluehost
>
>
>
> > On Mar 8, 2015, at 00:22, Alex Ayerdi <notifications@github.com> wrote:
> >
> > I think there is some forwarding setup on GoDaddy (I know, I know...) so
> we'll have to take that off once we have mysql access.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/153#issuecomment-77734602>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Harmonickey** [comment]
is there an advantage to switching the domain name to be held by bluehost rather than godaddy?

**Comment by Saurutobi** [comment]
not too much, it's just more consolidated. mostly price would be the
decider.

**Comment by Harmonickey** [comment]
aight, I have all the shit

**Comment by Harmonickey** [comment]
SQL migrated successfully.  nameserver switched successfully.  forwarding turned off.

**Comment by Harmonickey** [comment]
waiting on nameserver to propagate over the next few days

**Comment by Saurutobi** [comment]
nice! well done sir

**Comment by Harmonickey** [comment]
nevermind, that was quick, porting all files now

**Comment by Harmonickey** [comment]
Check it out, see if it all works for you

blastnu.org/wp-admin
u: admin
p: Vpssql061!

**Comment by Harmonickey** [comment]
test.blastnu.org created.  subdomain registered in bluehost, DNS subdomain registered as well with GoDaddy

**Comment by Harmonickey** [comment]
Next step is to get the test.blastnu.org site finished and then replace blastnu.org

**Comment by Saurutobi** [comment]
ok, since this ticket is don't I'll close it
