### ISSUE TITLE
Setup Chase Quickpay for ECCU

### ISSUE THREAD

**Issue by Harmonickey** [LbKStudios/lbkstudios-main#155]
I have the account setup.  It is now sending a test deposit to the bank and then Hami can use this quickpay account from now on to pay us.  The invoices through the bank will still say Data Gearbox LLC.

**Comment by Saurutobi** [comment]
Ok. Does quickpay have fees? Is it going to the ECCU account?

**Comment by Harmonickey** [comment]
quick pay is free, it is going directly to the ECCU account

On Mon, Mar 16, 2015 at 11:23 PM, Saurutobi <notifications@github.com>
wrote:

> Ok. Does quickpay have fees? Is it going to the ECCU account?
>
>
>
> > On Mar 17, 2015, at 00:17, Alex Ayerdi <notifications@github.com> wrote:
> >
> > I have the account setup. It is now sending a test deposit to the bank
> and then Hami can use this quickpay account from now on to pay us. The
> invoices through the bank will still say Data Gearbox LLC.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/155#issuecomment-82096868>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Harmonickey** [comment]
https://www.chase.com/index.jsp?pg_name=ccpmapp/individuals/shared/page/quickpay_faqs

**Comment by Harmonickey** [comment]
Not until July.
